runtime: nodejs16

env_variables:
  MONGODB_USER: MONGODB_USER
  MONGODB_PASSWORD: MONGODB_PASSWORD
  MONGODB_DB: MONGODB_DB
  LOGTAIL_TOKEN: LOGTAIL_TOKEN
  MONGODB_CLOUD_USER: MONGODB_CLOUD_USER
  MONGODB_CLOUD_PASSWORD: MONGODB_CLOUD_PASSWORD
  AMADEUS_CLIENT_ID: AMADEUS_CLIENT_ID
  AMADEUS_CLIENT_SECRET: AMADEUS_CLIENT_SECRET