export const Islands = [
  'Aruba',
  'Wallis and Futuna',
  'Åland Islands',
  'French Southern and Antarctic Lands',
  'Christmas Island',
  'Western Sahara',
  'Saint Martin',
  'Heard Island and McDonald Islands',
  'Antarctica',
  'Greenland',
  'British Indian Ocean Territory',
  'New Caledonia',
  'Niue',
  'Saint Barthélemy',
  'Puerto Rico',
  'Macau',
  'Isle of Man',
  'Curaçao',
  'Faroe Islands',
  'Montserrat',
  'Cook Islands',
  'Martinique',
  'Bermuda',
  'Cayman Islands',
  'Cocos (Keeling) Islands',
  'United States Virgin Islands',
  'Norfolk Island',
  'Bouvet Island',
  'American Samoa',
  'Anguilla',
  'Gibraltar',
  'Ivory Coast',
  'Jersey',
  'Saint Helena, Ascension and Tristan da Cunha',
  'Guernsey',
  'French Polynesia',
  'Falkland Islands',
  'Turks and Caicos Islands',
  'British Virgin Islands',
  'Guadeloupe',
  'Réunion',
  'Tokelau',
  'Sint Maarten',
  'United States Minor Outlying Islands',
  'French Guiana',
  'Saint Pierre and Miquelon',
  'Saint Vincent and the Grenadines',
  'South Georgia',
  'Caribbean Netherlands',
  'Svalbard and Jan Mayen',
  'Pitcairn Islands',
  'São Tomé and Príncipe',
  'Northern Mariana Islands',
  'Guam',
  'Mayotte',
];
