name: Deploy to App Engine

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: 73h/gae-app-yaml-replace-env-variables@v0.1
      env:
        MONGODB_USER: ${{ secrets.MONGODB_USER }}
        MONGODB_PASSWORD: ${{ secrets.MONGODB_PASSWORD }}
        MONGODB_DB: ${{ secrets.MONGODB_DB }}
        LOGTAIL_TOKEN: ${{ secrets.LOGTAIL_TOKEN }}
        MONGODB_CLOUD_USER: ${{ secrets.MONGODB_CLOUD_USER }}
        MONGODB_CLOUD_PASSWORD: ${{ secrets.MONGODB_CLOUD_PASSWORD }}
        AMADEUS_CLIENT_ID: ${{ secrets.AMADEUS_CLIENT_ID }}
        AMADEUS_CLIENT_SECRET: ${{ secrets.AMADEUS_CLIENT_SECRET }}
        IPGEOLOCATION_API_KEY: ${{ secrets.IPGEOLOCATION_API_KEY }}
        UNSPLASH_API_KEY: ${{ secrets.UNSPLASH_API_KEY }}
      with:
        app_yaml_path: "app.yaml"

    - name: Authenticate with Google Cloud
      run: |
        echo ${{ secrets.GCLOUD_SERVICE_KEY }} | base64 --decode > ${HOME}/gcloud-service-key.json
        gcloud auth activate-service-account --key-file ${HOME}/gcloud-service-key.json
        gcloud config set project ${{ secrets.GOOGLE_CLOUD_PROJECT }}

    - name: Set environment variables
      run: |
        echo "MONGODB_USER=${{ secrets.MONGODB_USER }}" >> $GITHUB_ENV
        echo "MONGODB_PASSWORD=${{ secrets.MONGODB_PASSWORD }}" >> $GITHUB_ENV
        echo "MONGODB_DB=${{ secrets.MONGODB_DB }}" >> $GITHUB_ENV
        echo "LOGTAIL_TOKEN=${{ secrets.LOGTAIL_TOKEN }}" >> $GITHUB_ENV
        echo "MONGODB_CLOUD_USER=${{ secrets.MONGODB_CLOUD_USER }}" >> $GITHUB_ENV
        echo "MONGODB_CLOUD_PASSWORD=${{ secrets.MONGODB_CLOUD_PASSWORD }}" >> $GITHUB_ENV
        echo "AMADEUS_CLIENT_ID=${{ secrets.AMADEUS_CLIENT_ID }}" >> $GITHUB_ENV
        echo "AMADEUS_CLIENT_SECRET=${{ secrets.AMADEUS_CLIENT_SECRET }}" >> $GITHUB_ENV

    - name: Install dependencies
      run: npm ci

    - name: Build application
      run: npm run build

    - name: Deploy to App Engine
      run: |
        gcloud app deploy --project=${{ secrets.GOOGLE_CLOUD_PROJECT }}
